### ISSUE TITLE
fix: connect navbar to links on same page with animation

### ISSUE THREAD

**Issue by mintbomb27** [MLA-VIT/landing-page#20]
<img width="620" alt="Screenshot 2022-01-24 at 9 57 20 PM" src="https://user-images.githubusercontent.com/22593204/150823204-2149c08a-0340-4e0a-ac5d-7b3bdeb7deea.png">

connect these links to the same place using # in landing page, add animation to that transition.

**Comment by samabraham2022** [comment]
done
