### ISSUE TITLE
design: update events section with new design

### ISSUE THREAD

**Issue by mintbomb27** [MLA-VIT/landing-page#22]
<img width="736" alt="Screenshot 2022-01-24 at 10 00 04 PM" src="https://user-images.githubusercontent.com/22593204/150823665-a3985594-f58a-483b-8816-de49321005e5.png">

- [ ] Change the design and layout
- [ ] add inner shadow
- [ ] Add carousel to events section moving three-three events at a delay of 3 seconds
- [ ] Fix Events component as mentioned in #19

**Comment by samabraham2022** [comment]
closed
