### ISSUE TITLE
fix: misalignment in newsletter, magazine section

### ISSUE THREAD

**Issue by mintbomb27** [MLA-VIT/landing-page#23]
<img width="1440" alt="Screenshot 2022-01-24 at 10 03 07 PM" src="https://user-images.githubusercontent.com/22593204/150824207-52ffc08e-6559-4f84-b04b-760a7bf5e453.png">

Match the code as per the design, fix the alignment issues.
<img width="745" alt="Screenshot 2022-01-24 at 10 05 31 PM" src="https://user-images.githubusercontent.com/22593204/150824677-394dea90-d7bd-417f-8c38-c0eafb4880ae.png">

**Comment by samabraham2022** [comment]
done
