### ISSUE TITLE
fix: footer issues

### ISSUE THREAD

**Issue by mintbomb27** [MLA-VIT/landing-page#24]
- [ ] Reduce the font size, and choose font as per the design (make the mail part light/regular)
- [ ] Bring the contact us part more towards the left
- [ ] Link the social handles with MLA's handles
- [ ] Make sure the logos have the same size (as per design)(except youtube)
- [ ] add more padding to the top and bottom
- [ ] fix typo in mail, and add mailto link: thanima@vit.ac.in
- [ ] Change LinkedIn Handle to GitHub
- [ ] Reduce thickness of the line

<img width="800" alt="Screenshot 2022-01-24 at 10 04 32 PM" src="https://user-images.githubusercontent.com/22593204/150824893-2b53dc84-92f1-455b-8141-5864dee1e2b1.png">
Design:
<img width="743" alt="Screenshot 2022-01-24 at 10 22 19 PM" src="https://user-images.githubusercontent.com/22593204/150827688-1724894e-ea25-44d8-b33c-da0539f94e70.png">

**Comment by mintbomb27** [comment]
MLA's handles:
Instagram: https://instagram.com/mla_oruma
Facebook: https://www.facebook.com/mlathanima/
GitHub: https://github.com/MLA-VIT
YouTube: https://www.youtube.com/channel/UCttLaZbCtMlWXpCDTrWN-mQ

**Comment by samabraham2022** [comment]
done
