### ISSUE TITLE
Distorted Landing Page

### ISSUE THREAD

**Issue by mintbomb27** [MLA-VIT/landing-page#5]
Check out the video.
[Issue](https://cdn.discordapp.com/attachments/856580866175139890/879793918152163358/Screen_Recording_2021-08-24_at_11.55.18_PM.mov)

The image must be cropped properly based on the screen height, and the position of the "Welcome to MLA" text as well as the background svg must change according to screen height. Basically, make it responsive.

**Comment by mintbomb27** [comment]
@the911guy Acknowledge

**Comment by the911guy** [comment]
@the911guy Ok, will work on that!
